version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: 04:00
      timezone: UTC
    allow:
      - dependency-type: all
    versioning-strategy: increase
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - npm
    reviewers: []
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: 04:30
      timezone: UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
